/**
 * The KaTeX stylesheet, trimmed to the font format the panel actually uses, plus its fonts.
 *
 * Run from the repository root after changing the katex version:
 *
 *   node scripts/katex-css.mjs
 *
 * Why generate rather than import `katex/dist/katex.min.css` straight: that file lists three formats for
 * every face - woff2, woff and ttf - and the bundler emits all sixty files it points at, about 1.1 MB, of
 * which the browser downloads only the woff2. The panel ships inside the plugin's archive and the phone
 * client inside the relay's image, so those 800 KB are carried to every user forever and read by nobody.
 * Trimmed to woff2 the whole set is 296 KB, next to the 360 KB the panel's own two families already cost.
 *
 * The fonts land in `webview/public/fonts` beside Instrument Sans and JetBrains Mono, and the rewritten
 * urls point at them from the root - the same way `src/fonts.css` addresses those two. The rest of the
 * stylesheet is copied as it is: it is KaTeX's own layout, and reading it is not our business.
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'webview/node_modules/katex/dist')
const fontsOut = join(root, 'webview/public/fonts')
const cssOut = join(root, 'webview/src/math/katex.css')

const version = JSON.parse(readFileSync(join(root, 'webview/node_modules/katex/package.json'), 'utf8')).version

// Every woff2 the current version of the library ships. A name outside this list is copied nowhere near as
// blindly as the trim below refuses a src list it does not recognise: an unnoticed file added by a future
// release - or, the reason this is checked at all rather than left to a diff nobody reads, by a version
// published under a compromised npm account - would otherwise ride straight into the plugin's archive and
// the phone client's image without a single line of this script objecting.
const EXPECTED_FONTS = new Set([
  'KaTeX_AMS-Regular.woff2',
  'KaTeX_Caligraphic-Bold.woff2',
  'KaTeX_Caligraphic-Regular.woff2',
  'KaTeX_Fraktur-Bold.woff2',
  'KaTeX_Fraktur-Regular.woff2',
  'KaTeX_Main-Bold.woff2',
  'KaTeX_Main-BoldItalic.woff2',
  'KaTeX_Main-Italic.woff2',
  'KaTeX_Main-Regular.woff2',
  'KaTeX_Math-BoldItalic.woff2',
  'KaTeX_Math-Italic.woff2',
  'KaTeX_SansSerif-Bold.woff2',
  'KaTeX_SansSerif-Italic.woff2',
  'KaTeX_SansSerif-Regular.woff2',
  'KaTeX_Script-Regular.woff2',
  'KaTeX_Size1-Regular.woff2',
  'KaTeX_Size2-Regular.woff2',
  'KaTeX_Size3-Regular.woff2',
  'KaTeX_Size4-Regular.woff2',
  'KaTeX_Typewriter-Regular.woff2',
])

mkdirSync(fontsOut, { recursive: true })
const fonts = readdirSync(join(dist, 'fonts')).filter((name) => name.endsWith('.woff2'))

const unexpected = fonts.filter((name) => !EXPECTED_FONTS.has(name))
if (unexpected.length > 0) {
  throw new Error(`unexpected font file(s) in katex's dist/fonts, not in EXPECTED_FONTS: ${unexpected.join(', ')}`)
}

// The other half of the same guard: a face renamed or dropped by a library update would otherwise pass
// silently here and only show up later as a formula quietly falling back to the wrong font on screen.
const missing = [...EXPECTED_FONTS].filter((name) => !fonts.includes(name))
if (missing.length > 0) {
  throw new Error(`expected font file(s) missing from katex's dist/fonts: ${missing.join(', ')}`)
}

for (const name of fonts) copyFileSync(join(dist, 'fonts', name), join(fontsOut, name))

// Only the woff2 url survives; the two that follow it in every src list go.
const source = readFileSync(join(dist, 'katex.min.css'), 'utf8')
const trimmed = source.replace(
  /src:url\(fonts\/([\w-]+)\.woff2\) format\("woff2"\)(?:,url\(fonts\/[\w-]+\.(?:woff|ttf)\) format\("(?:woff|truetype)"\))*/g,
  (_all, face) => `src:url(/fonts/${face}.woff2) format("woff2")`,
)

if (trimmed.includes('.woff)') || trimmed.includes('.ttf)')) {
  throw new Error('a woff or ttf url survived the trim - the src lists in katex.min.css have changed shape')
}

writeFileSync(
  cssOut,
  `/* Generated by scripts/katex-css.mjs from katex ${version}. Do not edit by hand. */\n${trimmed}\n`,
)

console.log(`katex ${version}: ${fonts.length} woff2 into public/fonts, stylesheet into src/math/katex.css`)
